### ISSUE TITLE
Cannot add tasks to a story

### ISSUE THREAD

**Issue by JulioFortunato** [Codeminer42/cm42-central#218] opened 2017-08-01 18:11 UTC
Console returns a 422 error while trying to use browser's autocomplete item as the name of a task. When the text is changed, like adding a blank space at the end of it, as seen on the following gif, the task is created successfully.

![addtaskbug](https://user-images.githubusercontent.com/4470902/28840899-d1cd0316-76ce-11e7-83a1-27b369104fca.gif)

**Comment by andrerpbts** [comment] 2017-09-13 18:22
Please, which browser are you using?

I've tried both on Firefox and Chrome, and the browser autocomplete behavior doesn't happen. And it is intended to not work with browser autocomplete since it has its own tag autocomplete implementation.

**Comment by andrerpbts** [comment] 2017-10-02 17:23
Closing this issue since we can't reproduce this bug for now.

If this happens again in the future, we'll reopen it.

**Closed by andrerpbts** 2017-10-02 17:23 UTC
